### ISSUE TITLE
Cant get addon to work. 8 errors.

### ISSUE THREAD

**Issue by Garduk** [Rycia/azeroth-pilot-reloaded#20] opened 2022-11-05 18:14 UTC
All mods disabled except azeroth pilot reloaded. Was gonna come back to WoW and level a zandalari for the heritage armor before launch of dragonflight but I just can't level without this addon!

Any help? Thanks!

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML: Binding
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML: Binding
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: name
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: header
Time: Sat Nov  5 19:08:02 2022
Count: 1

Message: Interface\FrameXML\Bindings.xml:1 Interface/AddOns/APR-Core/Bindings.xml:2 Unrecognized XML attribute: category
Time: Sat Nov  5 19:08:02 2022
Count: 1

**Comment by Pahonix** [comment] 2022-11-05 18:29
I believe these are fixed in the GitHub version, but just has not been pushed to CurseForge yet. Download dev ZIP on the main page (under the green code button) and give that a try.

**Comment by Garduk** [comment] 2022-11-05 18:46
Hmm yeah that fixed those errors. 

The addon doesn't do anything for me tho. Arrow doesn't work and quest list isn't populated. Trying to complete a quest to see if it updates but nothing.

**Comment by Pahonix** [comment] 2022-11-05 18:53
By default using the Speed Run, ARP should guide you 1-10 through Exile's Reach, then to Stormwind/Orgrimmar at level 10, then to Chromie to accept the Iron Horde (Warlords of Draenor) timeline.

If you do not have a subscription, that might mean you do not have a character already at level 50+ on your account, which means you cannot use Chromie to do the WoD timeline. Because of this, you will need to use the Custom Path feature to select the Battle for Azeroth (BFA) routes since without Chromie Time, the other zones won't scale with you (i.e., will stop giving you XP at a certain point), but the BFA ones will.

**Comment by deathmessinger** [comment] 2022-11-05 19:46
Yes that is because blizz changed shit up you cant use the keybind button you need to go into options>Keybind>addons it is in there
i am working on getting that fixed

**Comment by NightofStarrs** [comment] 2022-11-20 21:09
This is a duplicate of #13, closing issue - which should have been resolved with the newest version.

**Closed by NightofStarrs** 2022-11-20 21:09 UTC
Labels: Bug, Duplicate
