### ISSUE TITLE
Auto quest pick-up does not work with vendor NPCs

### ISSUE THREAD

**Issue by Velsera** [Rycia/azeroth-pilot-reloaded#16] opened 2022-11-02 03:18 UTC
Title. If a vendor NPC has a quest, APR does not automatically pick it up. Turn-in also does not work.

IE: Thaelin Darkanvil in Tanaan Jungle (WOD intro).

**Comment by Pahonix** [comment] 2022-11-02 03:53
Duplicate of #10. Stop posting duplicate issues.

**Closed by Pahonix** 2022-11-02 03:53 UTC
